In [2]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
[(1,2)] + [(3,4)]

[(1, 2), (3, 4)]

In [5]:
import torch
x = torch.randn(2, 3)

torch.cat((x, x, x), -1)

tensor([[ 1.1528,  0.3898, -0.3444,  1.1528,  0.3898, -0.3444,  1.1528,  0.3898,
         -0.3444],
        [-0.8716, -0.2491,  0.3150, -0.8716, -0.2491,  0.3150, -0.8716, -0.2491,
          0.3150]])

In [7]:
x.shape

torch.Size([2, 3])

In [8]:
torch.cat((x, x, x), -1).shape

torch.Size([2, 9])

In [10]:
torch.cat((x, x, x), 0).shape

torch.Size([6, 3])

In [15]:
l = [1,2,3,4]
l[1,-1]

TypeError: list indices must be integers or slices, not tuple

In [22]:
l[int(len(l)/2-1)] 

2

In [23]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [26]:
for i in range(3):
    print(i)

0
1
2


In [27]:
28*28

784

In [1]:
!python grader.py

Traceback (most recent call last):
  File "/Users/chenhuizhang/Desktop/MOOC/XCS330/XCS330-PS3-main/src/grader.py", line 9, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'


In [2]:
from collections import defaultdict
prototype_dict = defaultdict(list)
prototype_dict

defaultdict(list, {})

In [ ]:
prototype_dict[int(label_support)].append(images_support_emb[idx])